// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using TamagotchiSharp;
//
//    var cat = Cat.FromJson(jsonString);

namespace TamagotchiSharp
{
    using System;
    using System.Collections.Generic;

    using System.Globalization;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;

    public partial class Cat
    {
        [JsonProperty("breeds")]
        public List<Breed> Breeds { get; set; }

        [JsonProperty("height")]
        public long Height { get; set; }

        [JsonProperty("id")]
        public string Id { get; set; }

        [JsonProperty("url")]
        public Uri Url { get; set; }

        [JsonProperty("width")]
        public long Width { get; set; }
    }

    public class Breed
    {
        [JsonProperty("adaptability")]
        public long Adaptability { get; set; }

        [JsonProperty("affection_level")]
        public long AffectionLevel { get; set; }

        [JsonProperty("alt_names")]
        public string AltNames { get; set; }

        [JsonProperty("cfa_url")]
        public Uri CfaUrl { get; set; }

        [JsonProperty("child_friendly")]
        public long ChildFriendly { get; set; }

        [JsonProperty("country_code")]
        public string CountryCode { get; set; }

        [JsonProperty("country_codes")]
        public string CountryCodes { get; set; }

        [JsonProperty("description")]
        public string Description { get; set; }

        [JsonProperty("dog_friendly")]
        public long DogFriendly { get; set; }

        [JsonProperty("energy_level")]
        public long EnergyLevel { get; set; }

        [JsonProperty("experimental")]
        public long Experimental { get; set; }

        [JsonProperty("grooming")]
        public long Grooming { get; set; }

        [JsonProperty("hairless")]
        public long Hairless { get; set; }

        [JsonProperty("health_issues")]
        public long HealthIssues { get; set; }

        [JsonProperty("hypoallergenic")]
        public long Hypoallergenic { get; set; }

        [JsonProperty("id")]
        public string Id { get; set; }

        [JsonProperty("indoor")]
        public long Indoor { get; set; }

        [JsonProperty("intelligence")]
        public long Intelligence { get; set; }

        [JsonProperty("lap")]
        public long Lap { get; set; }

        [JsonProperty("life_span")]
        public string LifeSpan { get; set; }

        [JsonProperty("name")]
        public string Name { get; set; }

        [JsonProperty("natural")]
        public long Natural { get; set; }

        [JsonProperty("origin")]
        public string Origin { get; set; }

        [JsonProperty("rare")]
        public long Rare { get; set; }

        [JsonProperty("reference_image_id")]
        public string ReferenceImageId { get; set; }

        [JsonProperty("rex")]
        public long Rex { get; set; }

        [JsonProperty("shedding_level")]
        public long SheddingLevel { get; set; }

        [JsonProperty("short_legs")]
        public long ShortLegs { get; set; }

        [JsonProperty("social_needs")]
        public long SocialNeeds { get; set; }

        [JsonProperty("stranger_friendly")]
        public long StrangerFriendly { get; set; }

        [JsonProperty("suppressed_tail")]
        public long SuppressedTail { get; set; }

        [JsonProperty("temperament")]
        public string Temperament { get; set; }

        [JsonProperty("vcahospitals_url")]
        public Uri VcahospitalsUrl { get; set; }

        [JsonProperty("vetstreet_url")]
        public Uri VetstreetUrl { get; set; }

        [JsonProperty("vocalisation")]
        public long Vocalisation { get; set; }

        [JsonProperty("weight")]
        public Weight Weight { get; set; }

        [JsonProperty("wikipedia_url")]
        public Uri WikipediaUrl { get; set; }
    }

    public class Weight
    {
        [JsonProperty("imperial")]
        public string Imperial { get; set; }

        [JsonProperty("metric")]
        public string Metric { get; set; }
    }

    public partial class Cat
    {
        public static List<Cat> FromJson(string json) => JsonConvert.DeserializeObject<List<Cat>>(json, Converter.Settings);
    }

    public static class Serialize
    {
        public static string ToJson(this List<Cat> self) => JsonConvert.SerializeObject(self, Converter.Settings);
    }

    internal static class Converter
    {
        public static readonly JsonSerializerSettings Settings = new JsonSerializerSettings
        {
            MetadataPropertyHandling = MetadataPropertyHandling.Ignore,
            DateParseHandling = DateParseHandling.None,
            Converters =
            {
                new IsoDateTimeConverter { DateTimeStyles = DateTimeStyles.AssumeUniversal }
            },
        };
    }
}
